### ISSUE TITLE
Supports Login Authentication with Google

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/JaMmusic#18]
* [x] login and logout buttons
* [x] fix combined redux, combined reducers, mapstoretoprops, and removes console logs when production
* [x] already have profile, send different post for react google button, make changes to backend
* if email does not exist, need to verify with google in backend before creating new user
   -  [x] try sending various id tokens to google as the code in the api
   -  [x]  see what this api does in the react-google-login documentation, https://www.npmjs.com/package/react-google-login

* [x] send post to backend with json 
{
isOhafUser: false,
code: '4/RwGNOxx8gUcbHT8sB70BRJvPmlVs_crYo3pZHLR_Jt3MUiJRq5xxSw09XqtOXHA5tCBej4TCNw0ibKoJCojJtK8',
clientId: '702173574211-lo764q6i5k1c5brj29g28ltrjcbvq2hn.apps.googleusercontent.com',
redirectUri: 'http://localhost:9000',
state: 'yih7kp0bzhb'
 }

* [x] receive token back and put it into localStorage
* [x] code climate for google auth stuff
* [x] unit tests for google auth stuff
